name: ticketpedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  go_router: ^16.0.0
  intl: ^0.20.2
  syncfusion_flutter_datepicker: ^29.1.38

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - lib/assets/img/

flutter_gen:
  output: lib/assets/